version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      nodejs: 10
      dotnet: 2.2

    commands:
      - apt-get update
      - apt-get install -y python2.7 docker
      - apt-get install -y libgtk-3-dev libxss1 xvfb libnss3-dev libasound2 libasound2-plugins
      - pip install --user aws-sam-cli
      - pip install --upgrade awscli

  build:
    commands:
      - npm install
      - npm run compile
      - which sam
      - sam --version
      - env SAM_PROJECT_SDK='nodejs10.x' SAM_PROJECT_PATH='testProject/hello-world/app.js' xvfb-run npm run integrationTest
      #- env SAM_PROJECT_SDK='python2.7' SAM_PROJECT_PATH='testProject/hello_world/app.py' xvfb-run npm run integrationTest
      #- env SAM_PROJECT_SDK='python3.6' SAM_PROJECT_PATH='testProject/hello_world/app.py' xvfb-run npm run integrationTest
      #- env SAM_PROJECT_SDK='python3.7' SAM_PROJECT_PATH='testProject/hello_world/app.py' xvfb-run npm run integrationTest
      #- env SAM_PROJECT_SDK='dotnetcore2.1' SAM_PROJECT_PATH='testProject/src/HelloWorld/Function.cs' xvfb-run npm run integrationTest
    
